use crate::domain::{Account, PlayerConfig};
use anyhow::Result;

/// Render a MinecraftClient.ini (TOML) for the given player config.
///
/// MCC accepts TOML (it auto-detects legacy INI and converts). We emit TOML.
/// The behavior script is loaded at runtime via `script bot` over stdin, so we
/// do NOT need ScriptScheduler here; but we DO enable AutoRelog when requested.
pub fn render_ini(p: &PlayerConfig) -> Result<String> {
    let version = p
        .version_override
        .clone()
        .unwrap_or_else(|| "auto".to_string());

    let (login, password, account_type) = match &p.account {
        Account::Offline { username } => (username.clone(), "-".to_string(), "offline".to_string()),
        Account::Microsoft { login } => (login.clone(), "".to_string(), "microsoft".to_string()),
    };

    let server_addr = p.server.to_address();

    let mut s = String::new();
    s.push_str("# Generated by Leo's Minecraft AFK Helper.\n");
    s.push_str("# Minecraft Console Client (TOML) configuration.\n\n");

    // [Main.General]
    s.push_str("[Main.General]\n");
    s.push_str(&format!("Account = {{ Login = {}, Password = {} }}\n", tstr(&login), tstr(&password)));
    s.push_str(&format!("Server = {{ Host = {} }}\n", tstr(&server_addr)));
    if account_type != "offline" {
        s.push_str(&format!("AccountType = {}\n", tstr(&account_type)));
    }
    s.push_str("Method = \"mcc\"\n");
    s.push_str("\n");

    // [Main.Advanced]
    s.push_str("[Main.Advanced]\n");
    s.push_str(&format!("MinecraftVersion = {}\n", tstr(&version)));
    s.push_str("SessionCache = \"disk\"\n");
    s.push_str("ProfileKeyCache = \"disk\"\n");
    s.push_str("ExitOnFailure = true\n"); // required for subprocess supervision
    s.push_str("TerrainAndMovements = true\n");
    s.push_str("InventoryHandling = true\n");
    s.push_str("EntityHandling = true\n");
    s.push_str("AutoRespawn = true\n");
    s.push_str("Language = \"en\"\n");
    s.push_str("InternalCmdChar = \"slash\"\n");
    s.push_str("\n");

    // [AppVar] - disable Sentry telemetry by default (user can re-enable).
    s.push_str("[AppVar]\n");
    s.push_str("EnableSentry = false\n");
    s.push_str("\n");

    // [Console]
    s.push_str("[Console.General]\n");
    s.push_str("BasicIO = true\n");
    s.push_str("\n");

    // [ChatBot.AutoRelog]
    s.push_str("[ChatBot.AutoRelog]\n");
    s.push_str(&format!("Enabled = {}\n", p.auto_reconnect.enabled));
    s.push_str(&format!(
        "Delay = {{ min = {}, max = {} }}\n",
        fmt_f32(p.auto_reconnect.delay_min),
        fmt_f32(p.auto_reconnect.delay_max)
    ));
    s.push_str(&format!("Retries = {}\n", p.auto_reconnect.retries));
    s.push_str(&format!(
        "Ignore_Kick_Message = {}\n",
        p.auto_reconnect.kick_messages.is_empty()
    ));
    if !p.auto_reconnect.kick_messages.is_empty() {
        s.push_str("Kick_Messages = [");
        let items: Vec<String> = p
            .auto_reconnect
            .kick_messages
            .iter()
            .map(|m| tstr(m))
            .collect();
        s.push_str(&items.join(", "));
        s.push_str("]\n");
    }
    s.push_str("\n");

    Ok(s)
}

/// Quote a string for TOML.
fn tstr(s: &str) -> String {
    // Basic TOML basic-string escaping.
    let escaped: String = s
        .chars()
        .map(|c| match c {
            '"' => "\\\"".into(),
            '\\' => "\\\\".into(),
            '\n' => "\\n".into(),
            '\r' => "\\r".into(),
            '\t' => "\\t".into(),
            c if (c as u32) < 0x20 => format!("\\u{:04X}", c as u32),
            c => c.to_string(),
        })
        .collect();
    format!("\"{}\"", escaped)
}

fn fmt_f32(v: f32) -> String {
    // TOML floats need a decimal point or exponent.
    let s = format!("{}", v);
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{}.0", s)
    }
}
