use crate::domain::PlayerConfig;
use anyhow::Result;

/// Generate the final C# `//MCCScript` bot (`scripts/bot.cs`) from a PlayerConfig.
///
/// The user's `behaviors_csharp` is expected to be a complete `//MCCScript` file that
/// defines a class `AfkBot : ChatBot` with virtual hooks `OnUserJoin()`, `OnUserUpdate()`,
/// and `OnUserChat(string)`. The generator extracts that class body and emits a final
/// script where config-driven features (facing, on-join commands, auto-totem, force-quit)
/// are implemented in the sealed ChatBot overrides, calling the user's virtuals.
///
/// If the user's script is missing or malformed, we fall back to the default template so
/// the bot always loads.
pub fn generate_script(p: &PlayerConfig) -> Result<String> {
    let user_class = extract_user_class(&p.behaviors_csharp)
        .unwrap_or_else(|| default_user_class());

    let mut out = String::new();
    out.push_str("//MCCScript 1.0\n");
    out.push_str("// AUTO-GENERATED by Leo's Minecraft AFK Helper. Do not edit this file;\n");
    out.push_str("// edit the player's behavior in the app, then start/restart the player.\n");
    out.push_str("MCC.LoadBot(new AfkBot());\n\n");
    // NOTE: no `using` block here. MCC's script compiler (CSharpRunner.BuildScriptCode)
    // places everything after "//MCCScript Extensions" *inside* the generated `Script`
    // class, so `using` statements would be illegal there (CS1529). MCC injects all the
    // common usings (System, Regex, MinecraftClient.*, etc.) at the top of the namespace
    // itself, so they are not needed.
    out.push_str("//MCCScript Extensions\n");

    out.push_str("public class AfkBot : ChatBot\n");
    out.push_str("{\n");

    // ---- fields ----
    // Always emit _yaw/_pitch so Update()'s LookAtLocation(_yaw, _pitch) compiles even
    // when facing is disabled; _holdFacing gates the call at runtime.
    out.push_str(&format!(
        "    private readonly float _yaw = {}f;\n",
        fmt_f32(p.facing.map(|f| f.yaw).unwrap_or(0.0))
    ));
    out.push_str(&format!(
        "    private readonly float _pitch = {}f;\n",
        fmt_f32(p.facing.map(|f| f.pitch).unwrap_or(0.0))
    ));
    if p.facing.is_some() {
        out.push_str("    private readonly bool _holdFacing = true;\n");
    } else {
        out.push_str("    private readonly bool _holdFacing = false;\n");
    }

    // on-join command list
    out.push_str("    private static readonly string[] _onJoinCommands = new string[] {");
    if p.on_join_commands.is_empty() {
        out.push_str("};\n");
    } else {
        out.push('\n');
        for c in &p.on_join_commands {
            out.push_str(&format!("        {},\n", cstr(c)));
        }
        out.push_str("    };\n");
    }

    // on-join delay (in ticks, 20 ticks = 1 second)
    out.push_str(&format!(
        "    private readonly int _onJoinDelayTicks = {};\n",
        (p.on_join_delay_secs * 20.0).round() as i32
    ));

    // force-quit config flags
    out.push_str(&format!(
        "    private readonly bool _fqTotemPop = {};\n",
        p.force_quit.on_totem_pop
    ));
    out.push_str(&format!(
        "    private readonly bool _fqAttacked = {};\n",
        p.force_quit.on_attacked
    ));
    out.push_str(&format!(
        "    private readonly bool _fqDeath = {};\n",
        p.force_quit.on_death
    ));
    out.push_str(&format!(
        "    private readonly bool _fqLowHealth = {};\n",
        p.force_quit.low_health.is_some()
    ));
    out.push_str(&format!(
        "    private readonly float _fqLowHealthValue = {}f;\n",
        fmt_f32(p.force_quit.low_health.unwrap_or(0.0))
    ));
    out.push_str(&format!(
        "    private readonly bool _fqChatRegex = {};\n",
        p.force_quit.chat_regex.is_some()
    ));
    if let Some(rx) = &p.force_quit.chat_regex {
        out.push_str(&format!("    private readonly Regex _chatRegex = new Regex({}, RegexOptions.IgnoreCase);\n", cstr(rx)));
    } else {
        out.push_str("    private readonly Regex _chatRegex = null;\n");
    }

    // auto-totem + state
    out.push_str(&format!(
        "    private readonly bool _autoTotem = {};\n",
        p.auto_totem
    ));
    out.push_str("    private float _lastHealth = 20f;\n");
    out.push_str("    private bool _totemRefillScheduled = false;\n");

    out.push('\n');

    // ---- Initialize ----
    out.push_str("    public override void Initialize()\n    {\n");
    out.push_str("        LogToConsole(\"[AfkBot] loaded.\");\n");
    out.push_str("    }\n\n");

    // ---- AfterGameJoined ----
    out.push_str("    public override void AfterGameJoined()\n    {\n");
    out.push_str("        try {\n");
    out.push_str("            if (_onJoinDelayTicks > 0)\n");
    out.push_str("            {\n");
    out.push_str("                ScheduleOnMainThread(() =>\n");
    out.push_str("                {\n");
    out.push_str("                    foreach (var cmd in _onJoinCommands)\n");
    out.push_str("                    {\n");
    out.push_str("                        if (!string.IsNullOrEmpty(cmd)) SendText(cmd);\n");
    out.push_str("                    }\n");
    out.push_str("                    OnUserJoin();\n");
    out.push_str("                }, _onJoinDelayTicks);\n");
    out.push_str("            }\n");
    out.push_str("            else\n");
    out.push_str("            {\n");
    out.push_str("                foreach (var cmd in _onJoinCommands)\n");
    out.push_str("                {\n");
    out.push_str("                    if (!string.IsNullOrEmpty(cmd)) SendText(cmd);\n");
    out.push_str("                }\n");
    out.push_str("                OnUserJoin();\n");
    out.push_str("            }\n");
    out.push_str("        } catch (Exception e) { LogToConsole(\"[AfkBot] AfterGameJoined error: \" + e); }\n");
    out.push_str("    }\n\n");

    // ---- Update (20 TPS) ----
    out.push_str("    public override void Update()\n    {\n");
    out.push_str("        try {\n");
    out.push_str("            if (_holdFacing) LookAtLocation(_yaw, _pitch);\n");
    out.push_str("            if (_autoTotem) CheckAutoTotem();\n");
    out.push_str("            OnUserUpdate();\n");
    out.push_str("        } catch (Exception e) { LogToConsole(\"[AfkBot] Update error: \" + e); }\n");
    out.push_str("    }\n\n");

    // ---- OnHealthUpdate (attacked / low-health / death detection) ----
    out.push_str("    public override void OnHealthUpdate(float health, int food)\n    {\n");
    out.push_str("        try {\n");
    out.push_str("            bool dropped = health < _lastHealth - 0.01f && health > 0f;\n");
    out.push_str("            _lastHealth = health;\n");
    out.push_str("            if (_fqAttacked && dropped)\n");
    out.push_str("            { LogToConsole(\"[AfkBot] force-quit: attacked (health dropped).\"); ForceQuit(); return; }\n");
    out.push_str("            if (_fqLowHealth && health < _fqLowHealthValue)\n");
    out.push_str("            { LogToConsole(\"[AfkBot] force-quit: low health.\"); ForceQuit(); return; }\n");
    out.push_str("        } catch (Exception e) { LogToConsole(\"[AfkBot] OnHealthUpdate error: \" + e); }\n");
    out.push_str("    }\n\n");

    // ---- OnDeath ----
    out.push_str("    public override void OnDeath()\n    {\n");
    out.push_str("        try {\n");
    out.push_str("            if (_fqDeath)\n");
    out.push_str("            { LogToConsole(\"[AfkBot] force-quit: death.\"); ForceQuit(); return; }\n");
    out.push_str("        } catch (Exception e) { LogToConsole(\"[AfkBot] OnDeath error: \" + e); }\n");
    out.push_str("    }\n\n");

    // ---- OnPlayerStatus (totem pop = 35) ----
    out.push_str("    public override void OnPlayerStatus(byte statusId)\n    {\n");
    out.push_str("        try {\n");
    out.push_str("            if (statusId == 35)\n");
    out.push_str("            {\n");
    out.push_str("                LogToConsole(\"[AfkBot] totem of undying triggered.\");\n");
    out.push_str("                if (_fqTotemPop)\n");
    out.push_str("                { LogToConsole(\"[AfkBot] force-quit: totem pop.\"); ForceQuit(); return; }\n");
    out.push_str("                if (_autoTotem) ScheduleTotemRefill();\n");
    out.push_str("            }\n");
    out.push_str("        } catch (Exception e) { LogToConsole(\"[AfkBot] OnPlayerStatus error: \" + e); }\n");
    out.push_str("    }\n\n");

    // ---- GetText (chat regex force-quit + user hook) ----
    out.push_str("    public override void GetText(string text)\n    {\n");
    out.push_str("        try {\n");
    out.push_str("            string verbatim = GetVerbatim(text);\n");
    out.push_str("            if (!string.IsNullOrEmpty(verbatim))\n");
    out.push_str("            {\n");
    out.push_str("                if (_fqChatRegex && _chatRegex != null && _chatRegex.IsMatch(verbatim))\n");
    out.push_str("                { LogToConsole(\"[AfkBot] force-quit: chat regex matched.\"); ForceQuit(); return; }\n");
    out.push_str("                OnUserChat(verbatim);\n");
    out.push_str("            }\n");
    out.push_str("        } catch (Exception e) { LogToConsole(\"[AfkBot] GetText error: \" + e); }\n");
    out.push_str("    }\n\n");

    // ---- auto-totem helpers ----
    out.push_str("    private void ScheduleTotemRefill()\n    {\n");
    out.push_str("        if (_totemRefillScheduled) return;\n");
    out.push_str("        _totemRefillScheduled = true;\n");
    out.push_str("        ScheduleOnMainThread(() => { _totemRefillScheduled = false; CheckAutoTotem(true); }, 2);\n");
    out.push_str("    }\n\n");

    out.push_str("    private void CheckAutoTotem(bool force = false)\n    {\n");
    out.push_str("        try {\n");
    out.push_str("            if (!GetInventoryEnabled()) return;\n");
    out.push_str("            var inv = GetPlayerInventory();\n");
    out.push_str("            if (inv == null) return;\n");
    out.push_str("            bool offhandHasTotem = inv.Items.TryGetValue(45, out var offhand) && !offhand.IsEmpty && offhand.Type == ItemType.TotemOfUndying;\n");
    out.push_str("            if (offhandHasTotem && !force) return;\n");
    out.push_str("            // find a totem in the rest of the inventory (not slot 45)\n");
    out.push_str("            int src = -1;\n");
    out.push_str("            foreach (var kv in inv.Items)\n");
    out.push_str("            {\n");
    out.push_str("                if (kv.Key == 45) continue;\n");
    out.push_str("                if (!kv.Value.IsEmpty && kv.Value.Type == ItemType.TotemOfUndying) { src = kv.Key; break; }\n");
    out.push_str("            }\n");
    out.push_str("            if (src < 0) return;\n");
    out.push_str("            var helper = GetItemMovingHelper(inv);\n");
    out.push_str("            if (offhandHasTotem) helper.Swap(src, 45);\n");
    out.push_str("            else helper.MoveTo(src, 45);\n");
    out.push_str("            LogToConsole(\"[AfkBot] auto-totem: moved totem to off-hand (slot 45).\");\n");
    out.push_str("        } catch (Exception e) { LogToConsole(\"[AfkBot] auto-totem error: \" + e); }\n");
    out.push_str("    }\n\n");

    // ---- ForceQuit ----
    out.push_str("    private void ForceQuit()\n    {\n");
    out.push_str("        try { DisconnectAndExit(); } catch (Exception e) { LogToConsole(\"[AfkBot] ForceQuit error: \" + e); }\n");
    out.push_str("    }\n\n");

    // ---- user-defined virtual hooks (OnUserJoin / OnUserUpdate / OnUserChat) ----
    out.push_str(&indent(&user_class, "    "));
    out.push_str("}\n");

    Ok(out)
}

/// Re-indent a block of C# code to a uniform prefix, normalizing leading whitespace.
fn indent(src: &str, prefix: &str) -> String {
    let mut out = String::new();
    for line in src.lines() {
        let trimmed = line.trim_start();
        if trimmed.is_empty() {
            out.push('\n');
        } else {
            out.push_str(prefix);
            out.push_str(trimmed);
            out.push('\n');
        }
    }
    out
}

/// Extract the user's class-body members (the part after `class AfkBot : ChatBot {`
/// up to the matching closing brace) from their `//MCCScript` source, so we can inject
/// only their `OnUser*` virtual methods. If anything looks off, return None and the caller
/// uses the default class body.
fn extract_user_class(src: &str) -> Option<String> {
    if !src.starts_with("//MCCScript 1.0") {
        return None;
    }
    // Find "class AfkBot" (optionally with a base class).
    let key = "class AfkBot";
    let cls_idx = src.find(key)?;
    // Find the opening brace after the class declaration.
    let brace_idx = src[cls_idx..].find('{')?;
    let body_start = cls_idx + brace_idx + 1;

    // Walk braces to find the matching close.
    let bytes = src.as_bytes();
    let mut depth: i32 = 1;
    let mut i = body_start;
    while i < bytes.len() && depth > 0 {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => depth -= 1,
            b'"' => {
                // skip string literal
                i += 1;
                while i < bytes.len() {
                    if bytes[i] == b'\\' {
                        i += 2;
                        continue;
                    }
                    if bytes[i] == b'"' {
                        break;
                    }
                    i += 1;
                }
            }
            _ => {}
        }
        i += 1;
    }
    if depth != 0 {
        return None;
    }
    // body is src[body_start..i-1] (excluding the closing brace)
    let body = &src[body_start..i - 1];
    let body = body.trim();

    // Validate: the body must contain OnUserJoin, OnUserUpdate, and OnUserChat
    // method declarations (or the user's C# is broken and we should fall back).
    let has_join = body.contains("OnUserJoin");
    let has_update = body.contains("OnUserUpdate");
    let has_chat = body.contains("OnUserChat");
    if !has_join || !has_update || !has_chat {
        eprintln!("[scriptgen] user class body missing expected hooks; falling back to default");
        return None;
    }
    Some(body.to_string())
}

fn default_user_class() -> String {
    r#"    public virtual void OnUserJoin() { }
    public virtual void OnUserUpdate() { }
    public virtual void OnUserChat(string text) { }
"#
    .to_string()
}

/// C# string literal with proper escaping.
fn cstr(s: &str) -> String {
    let escaped: String = s
        .chars()
        .map(|c| match c {
            '"' => "\\\"".into(),
            '\\' => "\\\\".into(),
            '\n' => "\\n".into(),
            '\r' => "\\r".into(),
            '\t' => "\\t".into(),
            c => c.to_string(),
        })
        .collect();
    format!("\"{}\"", escaped)
}

/// Format an f32 for C# (ensure it looks like a float).
fn fmt_f32(v: f32) -> String {
    if v.is_nan() || v.is_infinite() {
        return "0".to_string();
    }
    let s = format!("{}", v);
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{}.0", s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::*;

    #[test]
    fn generates_valid_header_and_class() {
        let mut p = PlayerConfig::new("Test".into());
        p.auto_totem = true;
        p.force_quit.on_totem_pop = true;
        p.facing = Some(Facing { yaw: 90.0, pitch: 0.0 });
        p.on_join_commands = vec!["/gamemode survival".into()];

        let s = generate_script(&p).unwrap();
        assert!(s.starts_with("//MCCScript 1.0"));
        assert!(s.contains("MCC.LoadBot(new AfkBot());"));
        assert!(s.contains("//MCCScript Extensions"));
        assert!(s.contains("class AfkBot : ChatBot"));
        assert!(s.contains("statusId == 35"));
        assert!(s.contains("_autoTotem = true"));
        assert!(s.contains("helper.MoveTo(src, 45)"));
        assert!(s.contains("_yaw = 90.0f"));
        assert!(s.contains("\"/gamemode survival\""));
        assert!(s.contains("OnUserUpdate()"));
    }

    #[test]
    fn extracts_user_hooks() {
        let src = default_behavior_template();
        let body = extract_user_class(&src).unwrap();
        assert!(body.contains("OnUserJoin"));
        assert!(body.contains("OnUserUpdate"));
        assert!(body.contains("OnUserChat"));
    }

    #[test]
    fn falls_back_on_bad_header() {
        assert!(extract_user_class("not a script").is_none());
    }
}

